/**
 * Holds action types as constants
 */
const bookActionTypes = {
  FETCH_USER_BOOKS_START: 'FETCH_USER_BOOKS_START',
  FETCH_USER_BOOKS_SUCCESS: 'FETCH_USER_BOOKS_SUCCESS',

  FETCH_ALL_BOOKS_START: 'FETCH_ALL_BOOKS_START',
  FETCH_ALL_BOOKS_SUCCESS: 'FETCH_ALL_BOOKS_SUCCESS',
};

export default bookActionTypes;
